apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python app that displays time - named ${{values.app_name}}
  annotations:
    github.com/project-slug: jk7testorg/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: jk7testjenkins/${{values.app_name}}
    argocd/app-name: ${{values.app_name}}
spec:
  type: service
  owner: development

  lifecycle: experimental
